### PR TITLE
Enabled lint warnings for backend and client (fixes #491)

### LINKED ISSUE #491: Configure ESLint & Prettier for client-mvp-04
### Overview
Configure ESLint & Prettier for `client-mvp-04`

### PR DESCRIPTION
**Pull request by jasonwong26**
# Summary
- Reviewed Pial's lint rules from PR #582 and added them as warnings to client
- Made additional modifications to client `.eslintrc.json` file to remove unnecessary settings, clean up syntax, etc.
- Added basic linting rules to backend
- Converted all erroring rules to warnings (to be addressed later)

# Notes
This PR replaces the prior PR #582 (which was set to merge to the development branch).  Once this is approved and merged that PR can be closed as well.

### CODE REVIEW

**Review by drubgrubby — CHANGES_REQUESTED** [review]
@jasonwong26 ->  It seems to run Pial's lint rules and give only warnings, to which I say 'hooray'. 

in client: 
Screen Shot 2021-08-30 at 2 38 53 PM

In backend: 
Screen Shot 2021-08-30 at 2 39 36 PM

That said, when I try to run v 0.3 I get this: 
Screen Shot 2021-08-30 at 3 06 40 PM

It goes on for a while with more of the same.  So, either I'm missing something, or this isn't quite ready to merge yet. I give about equal weight to those two options.

**Comment by jasonwong26** [comment]
Hi @drubgrubby,

These changes are meant only for v0.4.  They aren't meant to be run within the v0.3 branch (though I can see us adding equivalent checks there).  Just to confirm, how did you run these rules against v0.3?  (Or maybe you meant v0.4 and there was a typo?)

**Comment by drubgrubby** [comment]
@jasonwong26 -> My confusion.  Because I'm switching back and forth between working on 0.3 and 0.4 , but in one view client and backend are 0.3 and in another view they are 0.4 I'm just getting used to what I'm looking at.  

So, yes, this was all run on 0.4 .  

Here's what I just did: 
- checked out your PR
- deleted node_modules directory and ran `yarn install` from root, client and backend directories. 
- ran `npm run start` from both the root and client directories (it works fine from backend)

I got the above `failed to compile` errors in both cases.  But since it's v0.4 I'm not sure what it is and isn't supposed to be doing at this point, so let me know if that's success or failure. 

The linting works great!  ;-)

**Comment by jasonwong26** [comment]
ok, let's discuss tonight - you shouldn't be getting compilation errors (or at least, I'm not in my environment).  Might be worth having a 3rd party see what their experience is.

**Comment by drubgrubby** [comment]
We have a better idea.
